from ubuntu

RUN apt-get update && apt install -y \
    nodejs npm \
    postgresql-client gcc python3-dev musl-dev \
    python3 python3-pip && \
    python3 -m pip install dumb-init
#    rm -rf /var/cache/apk/*

RUN npm install -g nodemon
RUN apt install libpq-dev python3-dev netcat -y
COPY ./requirements.txt /app/
RUN python3 -m pip install -r /app/requirements.txt


EXPOSE 8445
WORKDIR /app
CMD ["dumb-init", "/app/startup.sh"]
