"""track metrics

Revision ID: 3b0eac21d779
Revises: af4279aa1f64
Create Date: 2019-05-14 10:39:10.573393

"""

# revision identifiers, used by Alembic.
revision = '3b0eac21d779'
down_revision = 'af4279aa1f64'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics',
                    sa.Column('feature', sa.String(), nullable=False),
                    sa.Column('env', sa.String(), nullable=False),
                    sa.Column('date', sa.DATE(), nullable=False),
                    sa.Column('hit_count', sa.Integer(), server_default=sa.text('1'), nullable=False)
                    )
    op.create_index('metrics_index', 'metrics', ['feature', 'env', 'date'], unique=True)
    op.create_unique_constraint('deleted_feature_constraint', 'deleted_features', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('deleted_feature_constraint', 'deleted_features', type_='unique')
    op.drop_index('metrics_index', table_name='metrics')
    op.drop_table('metrics')
    # ### end Alembic commands ###
