"""release notes

Revision ID: c3be1b414b19
Revises: e9288c901c60
Create Date: 2019-06-03 16:55:05.216033

"""

# revision identifiers, used by Alembic.
revision = 'c3be1b414b19'
down_revision = 'e9288c901c60'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic ###
    op.create_table('release_notes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.Column('body', sa.Text(), nullable=True),
                    sa.Column('feature', sa.String(), nullable=True),
                    sa.Column('created_date', sa.TIMESTAMP(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_release_notes_feature'), 'release_notes', ['feature'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_index(op.f('ix_release_notes_feature'), table_name='release_notes')
    op.drop_table('release_notes')
    # ### end Alembic commands ###
