"""add rollouts

Revision ID: e9288c901c60
Revises: 3b0eac21d779
Create Date: 2019-05-20 09:54:52.711057

"""

# revision identifiers, used by Alembic.
revision = 'e9288c901c60'
down_revision = '3b0eac21d779'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rollout_users',
                    sa.Column('userid', sa.String(), nullable=False),
                    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('env', sa.String(), nullable=True)
                    )
    op.create_index(op.f('ix_rollout_users_env'), 'rollout_users', ['env'], unique=False)
    op.create_index(op.f('ix_rollout_users_features'), 'rollout_users', ['features'], unique=False)
    op.create_index(op.f('ix_rollout_users_userid'), 'rollout_users', ['userid'], unique=False)
    op.create_index(op.f('ix_metrics_env'), 'metrics', ['env'], unique=False)
    op.create_index(op.f('ix_metrics_feature'), 'metrics', ['feature'], unique=False)

    op.add_column('toggles', sa.Column('schedule', postgresql.JSONB(astext_type=sa.Text()),
                                       nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('toggles', 'schedule')
    op.drop_index(op.f('ix_metrics_feature'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_env'), table_name='metrics')
    op.drop_index(op.f('ix_rollout_users_userid'), table_name='rollout_users')
    op.drop_index(op.f('ix_rollout_users_features'), table_name='rollout_users')
    op.drop_index(op.f('ix_rollout_users_env'), table_name='rollout_users')
    op.drop_table('rollout_users')
    # ### end Alembic commands ###
