name:

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: build docker
      env:
          DOCKER_AUTH_CONFIG: ${{ secrets.DOCKER_AUTH_CONFIG }}
          CI_COMMIT_SHA: ${{ github.sha }}
      run: |
        mkdir -p /home/runner/.docker
        echo "$DOCKER_AUTH_CONFIG" > /home/runner/.docker/config.json
        docker build --pull -t "canopytax/toggle-meister:$CI_COMMIT_SHA" .
        docker push canopytax/toggle-meister:$CI_COMMIT_SHA

  test:
    needs: build
    runs-on: canopytax/toggle-meister:$CI_COMMIT_SHA

    steps:
    - name: test
      env:
        CI_COMMIT_SHA: ${{ github.sha }}
      run: |
        python --version
        ls
